#!/usr/bin/env bash
# Single-line per-core usage: "C0 7% | C1 3% | ..."
readarray -t a < <(grep -E '^cpu[0-9]+' /proc/stat)
sleep 0.5
readarray -t b < <(grep -E '^cpu[0-9]+' /proc/stat)

out=()
for i in "${!a[@]}"; do
  read -ra f1 <<< "${a[i]}"
  read -ra f2 <<< "${b[i]}"
  # fields: cpuN user nice system idle iowait irq softirq steal
  t1=$(( ${f1[1]}+${f1[2]}+${f1[3]}+${f1[4]}+${f1[5]}+${f1[6]}+${f1[7]}+${f1[8]} ))
  t2=$(( ${f2[1]}+${f2[2]}+${f2[3]}+${f2[4]}+${f2[5]}+${f2[6]}+${f2[7]}+${f2[8]} ))
  i1=$(( ${f1[4]}+${f1[5]} ))
  i2=$(( ${f2[4]}+${f2[5]} ))
  dt=$(( t2 - t1 ))
  di=$(( i2 - i1 ))
  use=$(( dt > 0 ? (100*(dt - di))/dt : 0 ))
  out+=( "C${i} ${use}%" )
done

printf "%s\n" "${out[@]}"